### PR TITLE
Add a prefix space manually

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
I'm not completely sure of this, but in a simple test, this hack results in a match with the Python output.  Python is keeping track of some compatibility settings for use with legacy tokenizers and doing the complaining.  It wants the pre_tokenizer to be using the add_prefix_space.  However, we're tokenizing manually.  If Scala adds the space manually and then calls this particular Rust tokenizer, it appears to treat the added spaces just as it might treat its own pre_tokenizer added spaces.  It seems worth trying it out.

**Comment by MihaiSurdeanu** [comment]
It doesn't seem to work correctly. When using the roberta_base model, the (incorrect) output is:
```
[info] Words: EU, rejects, German, call, to, boycott, British, lamb, .
[info] return java 8 instance
[info] Labels: B-ORG, O, O, O, O, O, O, O, O
[info] Labels: NNP, NNS, NN, NN, NN, NNS, NN, NN, NNP
[info] Labels: B-NP, B-NP, B-NP, B-NP, B-NP, B-NP, B-NP, B-NP, O
[info] Labels: 0, 0, -1, -1, -1, -1, -1, 0, -1
```

With bert, the correct output is:
```
[info] Words: EU, rejects, German, call, to, boycott, British, lamb, .
[info] return java 8 instance
[info] Labels: B-ORG, O, B-MISC, O, O, O, B-MISC, O, O
[info] Labels: NNP, VBZ, JJ, NN, TO, VB, JJ, NN, .
[info] Labels: B-NP, B-VP, B-NP, I-NP, B-VP, I-VP, B-NP, I-NP, O
[info] Labels: 1, 0, 1, -2, 1, -4, 1, -2, -7
```

**Comment by kwalcock** [comment]
We may have to talk in order for me to understand what is going on.  From just the tokenizer in the Python code in a completely different project I get

```
roberta-base (using add_prefix_space = True)
[0, 1281, 24020, 1859, 486, 7, 13978, 1089, 17988, 479, 2]
[None, 0, 1, 2, 3, 4, 5, 6, 7, 8, None]
['<s>', 'ĠEU', 'Ġrejects', 'ĠGerman', 'Ġcall', 'Ġto', 'Ġboycott', 'ĠBritish', 'Ġlamb', 'Ġ.', '</s>']

bert-base-cased (using add_prefix_space = False)
[101, 7270, 22961, 1528, 1840, 1106, 21423, 1418, 2495, 12913, 119, 102]
[None, 0, 1, 2, 3, 4, 5, 6, 7, 7, 8, None]
['[CLS]', 'EU', 'rejects', 'German', 'call', 'to', 'boycott', 'British', 'la', '##mb', '.', '[SEP]']
```

From Rust code, also in an independent project, using text with manually added spaces in the first case and not in the second, I get

```
let encoding = tokenizer.encode(&[" EU", " rejects", " German", " call", " to", " boycott", " British", " lamb", " ."][..], true)?; // spaces were added for this one

"roberta-base"
["<s>", "ĠEU", "Ġrejects", "ĠGerman", "Ġcall", "Ġto", "Ġboycott", "ĠBritish", "Ġlamb", "Ġ.", "</s>"]
[0, 1281, 24020, 1859, 486, 7, 13978, 1089, 17988, 479, 2]
[None, Some(0), Some(1), Some(2), Some(3), Some(4), Some(5), Some(6), Some(7), Some(8), None]

"bert-base-cased", so _no_ spaces added
["[CLS]", "EU", "rejects", "German", "call", "to", "boycott", "British", "la", "##mb", ".", "[SEP]"]
[101, 7270, 22961, 1528, 1840, 1106, 21423, 1418, 2495, 12913, 119, 102]
[None, Some(0), Some(1), Some(2), Some(3), Some(4), Some(5), Some(6), Some(7), Some(7), Some(8), None]
```
These values also match those in TokenizerTest from this branch.  So, I'm not sure what's wrong.  I probably don't understand what models are being used.

**Comment by kwalcock** [comment]
Could you print out the tokenIds that you are getting?

**Comment by MihaiSurdeanu** [comment]
In the main branch, the Tokenization.toString reports:
```
[info] Words: EU, rejects, German, call, to, boycott, British, lamb, .
[info] TOKENIZATION: tokenIds: [0, 14707, 241, 21517, 29, 27709, 16395, 560, 9902, 17083, 24270, 5112, 428, 4, 2]
[info] wordIds: [-1, 0, 1, 1, 1, 2, 3, 4, 5, 5, 6, 7, 7, 8, -1]
[info] tokens: ["<s>", "EU", "re", "ject", "s", "German", "call", "to", "boy", "cott", "British", "lam", "b", ".", "</s>"]
```

In this branch, this returns:
```
[info] TOKENIZATION tokenIds: [0, 14707, 241, 21517, 29, 27709, 16395, 560, 9902, 17083, 24270, 5112, 428, 4, 2]
[info] wordIds: [-1, 0, 1, 1, 1, 2, 3, 4, 5, 5, 6, 7, 7, 8, -1]
[info] tokens: ["<s>", "EU", "re", "ject", "s", "German", "call", "to", "boy", "cott", "British", "lam", "b", ".", "</s>"]
```

They seem identical to me... More interestingly, they seem correct in *both* cases... Maybe the bug is somewhere else, not in the tokenizer? I'll look into this more.

**Comment by kwalcock** [comment]
This output looks like "roberta-base" with addPrefixSpace = false, which may not be what you want.

**Comment by MihaiSurdeanu** [comment]
how do I set it to true?

**Comment by kwalcock** [comment]
I'm not sure which branch you are working on, but with the code from this branch, which is separate from the cleanPython branch, it would be

```scala
val tokenizer = ScalaJniTokenizer("roberta-base", addPrefixSpace = true)
```
It may be that I should do some merging or some cherry picking of commits needs to happen to get the changes to where you are working.  (And the hack could just be wrong, of course.)  I think this PR is source-compatible with main, so I could just merge it.

**Comment by MihaiSurdeanu** [comment]
Thanks! The new tokens are:
```
info] TOKENIZATION tokenIds: [0, 1281, 24020, 1859, 486, 7, 13978, 1089, 17988, 479, 2]
[info] wordIds: [-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, -1]
[info] tokens: ["<s>", "ĠEU", "Ġrejects", "ĠGerman", "Ġcall", "Ġto", "Ġboycott", "ĠBritish", "Ġlamb", "Ġ.", "</s>"]
```

**Comment by MihaiSurdeanu** [comment]
This is different, which should be good!

**Comment by kwalcock** [comment]
Those match Scala values in TokenizerTest and the earlier ones from Python and Rust, so they are what I hope works with the model.

**Comment by MihaiSurdeanu** [comment]
Can you please merge this branch into "scala"? The latter has more code for the Scala inference. I'd like to test in that context.

**Comment by kwalcock** [comment]
It was #23 and has been merged into scala.

**Pull request merged**
