### PR TITLE
Primal/dual inference in Scala

### PR DESCRIPTION
**Pull request by MihaiSurdeanu**

### CODE REVIEW

**Comment by kwalcock** [comment]
One can reproduce with `Test/compile`:

```
[error] D:\Users\kwa\Documents\MyData\Projects\clulab\scala-transformers-project\scala-transformers\encoder\src\test\scala\org\clulab\scala_transformers\encoder\timer\TokenClassifierTimerApp.scala:37:34: overloaded method value predict with alternatives:
[error]   (inputBatch: Array[breeze.linalg.DenseMatrix[Float]],batchHeads: Option[Array[Array[Int]]],batchMasks: Option[Array[Array[Boolean]]])Array[Array[String]] <and>
[error]   (inputSentence: breeze.linalg.DenseMatrix[Float],heads: Option[Array[Int]],masks: Option[Array[Boolean]])Array[String]
[error]  cannot be applied to (breeze.linalg.DenseMatrix[Float])
[error]           val tokenLabels = task.predict(encOutput)
[error]                                  ^
[error] one error found
```

**Comment by MihaiSurdeanu** [comment]
I pushed a fix. Hopefully.

**Comment by kwalcock** [comment]
I have an old email that says the maven size limit was 1GB, so it will be great to be under.

**Comment by MihaiSurdeanu** [comment]
@kwalcock : can you please look at why it fails now?
Thanks!

**Comment by kwalcock** [comment]
Yes.  There is also another, separate PR being prepared that takes care of Scala 3.  At the time this project was made, only Scala 2.13 was used in processors and in the meantime it has advanced.

**Comment by MihaiSurdeanu** [comment]
@kwalcock : can you please check and merge this PR?
Thank you!

**Comment by kwalcock** [comment]
I will merge #27 into this, then do some testing, and then merge this one.  It shouldn't take long.

**Pull request merged**
