### PR TITLE
Revert to concat

### PR DESCRIPTION
**Pull request by MihaiSurdeanu**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@kwalcock : Can you please review and merge?

**Comment by kwalcock** [comment]
I'd like to add some comments to build.sbt to explain that model version 0.1.0 is for when USE_CONCAT is true and that there are other versions for when it is false.  I'm likely to forget how it works otherwise.

**Comment by MihaiSurdeanu** [comment]
good idea!

**Review by kwalcock — APPROVED** [review]
It occurs to me that
```scala
val USE_CONCAT = true
```
leaves no way to change the value at runtime.  Is this switch only for developers or should people who are using the library be able to change the value before using a LinearLayer to get the alternative behavior?  If so, then it might need to be a var instead.

I will edit the CHANGES file, etc., before publishing again.

**Comment by MihaiSurdeanu** [comment]
> It occurs to me that
> 
> ```scala
> val USE_CONCAT = true
> ```
> 
> leaves no way to change the value at runtime. Is this switch only for developers or should people who are using the library be able to change the value before using a LinearLayer to get the alternative behavior? If so, then it might need to be a var instead.
> 
> I will edit the CHANGES file, etc., before publishing again.

That is intentional. I would prefer that just us change this.

**Comment by kwalcock** [comment]
Sounds good.  Merging.  I should have asked if you do need it published.

**Comment by MihaiSurdeanu** [comment]
Thanks! And, yes, please publish it so I can't update the processors branch.

**Pull request merged**
