### PR TITLE
Fix App

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
I will at some time suggest that these tasks be collected into some object like a Job so that a check can be done: if anything is dual, then there must be one head task.  The head task name will be checked then instead of during predict.  There may also be two kinds of LinearLayers, because the signature of predict is not the same for the dual ones.

**Comment by MihaiSurdeanu** [comment]
I have mixed feelings about the Job class. Seems like too much indirection for a simple API...
I agree with splitting the LinearLayer into two!

**Comment by kwalcock** [comment]
Yes, of course.  Only if it turns out to be useful.  If I understand it correctly, something should be checking that a head, probably exactly one, is required if there are any dual tasks and that the head itself cannot be dual.  Things like that.

**Comment by kwalcock** [comment]
@MihaiSurdeanu, this can be merged into your scala branch.  (I usually don't do it myself so that it doesn't happen at an inopportune time.)

**Comment by MihaiSurdeanu** [comment]
This looks good! Can you please merge it yourself?

**Comment by kwalcock** [comment]
Done, but don't forget to pull then.

**Pull request merged**
