### PR TITLE
Register a second opinion on Python code

### PR DESCRIPTION
**Pull request by kwalcock**
Before it gets out of hand, I'm turning in a draft.

### CODE REVIEW

**Review by MihaiSurdeanu — APPROVED** [review]

**Comment by kwalcock** [comment]
It looks like this was done once before and left in branch [kwalcock/training](https://github.com/clulab/scala-transformers/tree/kwalcock/training).  Perhaps I abandoned it there, where it is very much out of date.

There wasn't much instruction for the task, so here are some of the things being done, mostly to make it look like native Python code and be understandable, maintainable, efficient, etc.  It doesn't look like there are any real showstoppers, so the code could be left as is.  If anything here looks bad, me finding out would reduce the need to backtrack.

- [ ] add type hinting for methods and class variables
- [ ] standardize on 4-space indentation
- [ ] clean up (unused) imports, alphabetize
- [ ] add
    - [ ] README
    - [ ] requirements.txt
    - [ ] integration test
- [ ] standardize on double quotes
- [ ] use UTF-8 for files
- [ ] open files using "with" so they automatically close
- [ ] replace string addition with f"{}"
- [ ] use items() and values() when iterating through collections
- [ ] move globals into classes
- [ ] change configuration to parameters due to other config

The files may eventually be turned into a Python package what can be distributed independent of GitHub, like we use maven to distribute the Scala parts.  Then people can just pip install it.

FYI @MihaiSurdeanu

**Comment by kwalcock** [comment]
- [ ] use classes with named members instead of tuples
- [ ] factor out names/strings shared across different files
- [ ] put Trainers into a class hierarchy

**Comment by kwalcock** [comment]
This is far enough along, perhaps too far, that I don't have anything left on my list except to package it more cleanly.  However, it would be good to get a better feel for how it will be re-used for training other models, as if it was a library for that purpose.  How would the configuration be changed, where will the data files be kept, etc.  So, I'm ready to wait and see what happens.  Changes can be undone, of course.  I'm not certain that it is working exactly the same as before, especially for the averaging_trainer.  An even smaller test set is needed for a unit test, I think.

FYI @MihaiSurdeanu

**Comment by MihaiSurdeanu** [comment]
I'll take another look soon.

**Review by MihaiSurdeanu — APPROVED** [review]
LGTM!

**Comment by kwalcock** [comment]
Git is confused.  I'm going to have to close and do it differently.

**Pull request closed without merging**
