### PR TITLE
Checking for max tokens being exceeded in the encoder

### PR DESCRIPTION
**Pull request by MihaiSurdeanu**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@kwalcock : once merged, I think this deserves a release with a new minor version?

**Comment by MihaiSurdeanu** [comment]
Also, which deberta model version contains the encoder.maxtokens file?
Thanks!

**Comment by kwalcock** [comment]
Hi,

It should be the deberta-onnx-model version 0.1.0.

Keith

**Review by kwalcock — APPROVED** [review]
LGTM

**Comment by kwalcock** [comment]
So probably that model needs to be updated in the build file to this project.  I will do that and make sure it still passes.

**Comment by kwalcock** [comment]
It's a good thing it's nearly impossible to go back and correct typos in the commit messages.

**Pull request merged**
