### PR TITLE
Load models from resources

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
Despite having 32 processors in this computer, the parallel version was only about 2x as fast as the serial.  However, the serial was pretty fast already.  This is on ~~1000~~ 10,000 sentences.

| Run | Time |
| --- | --: |
| serial | 0:00:03:11.941 |
| parallel | 0:00:01:38.621 |

**Comment by MihaiSurdeanu** [comment]
Nice! This means approximately 0.2 secs/sentence. Do you have equivalent results with dynet?

**Comment by kwalcock** [comment]
The key changes for users are

https://github.com/clulab/scala-transformers/blob/e409ba4f15da5a08e80321987f5ba8e71b77a8ba/encoder/build.sbt#L17

and

https://github.com/clulab/scala-transformers/blob/e409ba4f15da5a08e80321987f5ba8e71b77a8ba/encoder/src/main/scala/org/clulab/scala_transformers/encoder/apps/TokenClassifierExampleApp.scala#L13-L14

**Review by MihaiSurdeanu — APPROVED** [review]
LGTM @kwalcock !

**Comment by kwalcock** [comment]
For the current CluProcessor and tokenization through annotation, these are the times:

| Run | Time |
| --- | --: |
| Serial | 0:00:08:30.653 |
| Parallel | 0:00:09:53.833	|

For this run and last one, the number of sentences is 10,000 rather than just 1000.  At some point in the past I hadn't wanted to wait so long for the results and truncated the list and then I read the wrong source file.  I double checked this time.

Parallel might be worse than serial because there is minimal gain in parallelization and managing 32 processors has too high an overhead.  It might be better if I limited it to 2 or 3.

So, the new version may be 3-6 times faster.

**Comment by MihaiSurdeanu** [comment]
Can you please check with 2 and 3 nodes?

**Comment by kwalcock** [comment]
What is a node?  It looks like CluProcessor has neural networks associated with these values:

* lazyMtlPosChunkSrlp
* lazyMtlNer
* lazyMtlSrla
* lazyMtlDepsHead
* lazyMtlDepsLabel

**Comment by kwalcock** [comment]
Oh, I think you mean processors.  Will do.

**Comment by kwalcock** [comment]
CluProcessor isn't getting anything out of multi-threading during the tokenization and annotation.  The gains in Eidos might have been from the extraction engine part then.

| Threads | Time |
| --- | --: |
| 1 | 0:00:08:30.653 |
| 2 | 0:00:09:48.338 |
| 3 | 0:00:09:30.924 |

**Comment by MihaiSurdeanu** [comment]
Is this the current stable CluProcessor with fatdynet, or the scala-transformer model?

**Comment by kwalcock** [comment]
Current CluProcessor with dynet.

**Comment by MihaiSurdeanu** [comment]
Thanks! If you run the same sentences with the TokenClassifier, what runtimes do you observe?
If it's too complicated, this can wait until I finish the new processor that uses it.

**Comment by kwalcock** [comment]
I'm not sure what you mean.  The first numbers on this page used the TokenClassifier of this project.  The actual tokens were created with `line.split(" ")` rather than the Tokenizer from processors.  Should I use the real tokenizer in place of line.split?

**Comment by MihaiSurdeanu** [comment]
Ah sorry! I forgot about those :)
That experiment is meaningful, and is what I had in mind. For the sake of a fair comparison, can you please repeat it with 2 and 3 processors?

**Comment by kwalcock** [comment]
Below is what has been measured to far.  It looks like the difference between the fake and real tokenizers can hide within the variance of different runs.  I'm having difficulty with the "those", "that", and "it".  What needs to be added?

Threads | Transformer time (fake tokenizer) | Transformer time (real tokenizer) | CluProcessor time (fake tokenizer)
-- | -- | -- | --
1 | 0:00:03:11.941 | 0:00:03:05.631 | 0:00:08:30.653
2 | 0:00:02:16.122 | 0:00:02:18.736 | 0:00:09:48.338
3 | 0:00:02:13.802 | 0:00:02:00.083 | 0:00:09:30.924
32 | 0:00:01:38.621 | 0:00:01:33.533 | 0:00:09:53.833

**Comment by MihaiSurdeanu** [comment]
Thanks! This is great! No other experiments needed here.

**Pull request merged**
