### PR TITLE
Train the transformers

### PR DESCRIPTION
**Pull request by kwalcock**
This is being submitted as a draft to facilitate discussion

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Let's not merge this yet. I need to push a few more things.

**Comment by kwalcock** [comment]
I was asked to look, and the code here didn't look at all bad, but there isn't much Python code in the clulab repos that shows what it should look like.  If I had to be prescriptive about it, I would like exemplary Python code (that might serve as an example, be read by others, be copied) to use type hinting for all functions/methods and to not have more than one global variable or function per file, the one corresponding to the companion object in Scala.  This also needs a requirements file (`requirements.txt`) in which all the dependencies and their versions are specified.  I don't know what versions are being used, so this should probably be made on Mihai's computer.  I was editing the files to fit the "rules" and see if they work reasonably and what should be added, but before I get too far, they should get written down in case that's not the way to go.  The files being updated are in the branch https://github.com/clulab/scala-transformers/tree/kwalcock/training/encoder/src/main/python.

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock !

- I like the idea of reducing global variables! Maybe they can be stored in Config class instead?
- I haven't done type  hinting in Python yet. If you have an example, it will help.
- I will add a requirements file soon(ish).

Thanks!

**Comment by kwalcock** [comment]
My branch is incomplete and untested, but the [Configuration](https://github.com/clulab/scala-transformers/blob/kwalcock/training/encoder/src/main/python/configuration.py) class encapsulates some global variables to be accessed as config.epochs as shown in [data_wrangling.py](https://github.com/clulab/scala-transformers/blob/kwalcock/training/encoder/src/main/python/data_wrangling.py) which has partial hinting for the functions.  The functions are global, so they will be moved to a DataWrangler.

**Comment by MihaiSurdeanu** [comment]
Please wait with the merging for ~1 more day. I need to push a few more things.

**Pull request merged**
